### ISSUE TITLE
1. A New Challenger Appears!

### ISSUE THREAD

**Issue by SaifMurtaza** [MakeSchool-Tutorials/Intro-Functions-Challenge#2]
Hi is this down? 

Im trying to attempt the challenge

P.S - you guys should add in full solutions to the challenges at the very end. This way we can double check our own code after trying the challenge

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/Intro-Functions-Challenge-Playground/commit/f762bf811aaa8d05aef5f97aee04d55bce0997b5
