### ISSUE TITLE
1. A New Challenger Appears!

### ISSUE THREAD

**Issue by YukiKawamura0211** [MakeSchool-Tutorials/Intro-Functions-Challenge#4]
we can't download this file at all. 
so I wonder if anyone could fix it or known how to download it...
thanks!

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/Intro-Functions-Challenge-Playground/commit/f762bf811aaa8d05aef5f97aee04d55bce0997b5
